### ISSUE TITLE
improve outputUnits with all assertion fields 

### ISSUE THREAD

**Issue by JR-Utily** [networknt/json-schema-validator#1030]
Thanks for your great lib.
We needed json schema validation for our scala project, and it was really easy to wrap around your work !

I have one suggestion regardless: 
You have documented a lot of interesting fields available for the "assertion" object here
https://github.com/networknt/json-schema-validator?tab=readme-ov-file#results-and-output-formats
that are in fact only available in the `ValidationMessage` class and not in `OutputUnit` for LIST or HIERARCHY validation.
It would be great to have them, for example to be able to built our own error message from the given errors without the need to rely on the lib specific formulation.

In this view, I think `OutputUnit.getErrors` and `OutputUnit.getAnnotations` could return something with stronger type than just `Map<String, Object>` to give structure, in a way close to what already exists in `ValidationMessage`

I hope it helps improve this great lib !

**Comment by justin-tay** [comment]
The output unit needs to serialize the errors to the message to implement [A Specification for Machine-Readable Output for JSON Schema Validation and Annotation](https://github.com/json-schema-org/json-schema-spec/blob/8270653a9f59fadd2df0d789f22d486254505bbe/jsonschema-validation-output-machines.md) so that won't change.

It's also not really possible to return a stronger type, as the type varies and `Object` is the only shared super type.

If the issue is that you would like the ability to customize the messages for those formats then I can see if something can be exposed to do so.

**Comment by JR-Utily** [comment]
Well, I didn't interpret the spec as you did, but I get your point.
IMHO, the format given for LIST and HIERACHY are examples, not what MUST be implemented. When it says " however it is RECOMMENDED that the output be convertible to the JSON format defined herein via serialization or other means. " it does not say the error message has to be already formulated in one locale in output units, only that it should be easily serializable in json (and most struct data are).
BUT this is just my opinion, and I see what you did in the PR, which is great.
If I understand correctly, it will allow to pass a function to instantiate any Class from a ValidationMessage so that Class would be put in the getErrors() Map ?
If so, it is really great, and I must thank you for the quickness of the patch !
