### ISSUE TITLE
validation of date fields

### ISSUE THREAD

**Issue by pallaviterala** [networknt/json-schema-validator#138]
Hi,

The date fields are not being validated correctly by framework. If an invalid date is provided in request, it's still not throwing any validation error.

e.g.: 2019-02-29

And for valid dates, the body map returned by BodyHandler is holding a String object instead of a Date object. If this map contains Date object, we can avoid parsing String to Date in APIs.

Regards,
Pallavi

**Comment by stevehu** [comment]
In the JSON schema specification, the date is only validated with a regular expression to ensure that the format is correct. Given that we have enhanced this library a lot based on the requirement from our customers, I think it makes sense to implement additional validation for Date type. However, the extra validation might slow down the validation process for most users who have a valid date format coming from a standalone application or a Javascript SPA with a DatePicker. I would recommend making this additional validation configurable so that it can be enabled by the user if they have clients application that allows users to enter date as a string.

**Comment by ddobrin** [comment]
Agreed with making it config-based

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [validation of date fields](https://trello.com/c/3VJNBPnt/238-validation-of-date-fields)
