### ISSUE TITLE
validation for enum object type

### ISSUE THREAD

**Issue by chenyan71** [networknt/json-schema-validator#142]
Based on current light-codegen, if user want to generate separate enum type object from openapi specification, the enum need define as type "object" in the spec. For example:
    CurrencyCode:
      type: object
      enum:
        - CAD
        - USD
        - EUR

But in this case, system get validation error for the enum object type.

**Comment by stevehu** [comment]
I think we need to stick to object type in the light-codegen and have a fix in the json-schema-validator. Basically we need to allow the object type in the schema but validate the values based on the string. As this is not standard in json schema, we need to put this into the configuration so that users will have an option to turn it off.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [validation for enum object type](https://trello.com/c/wFXvNPtM/215-validation-for-enum-object-type)
