### ISSUE TITLE
Validation error when field is nullable and consumer sends in a null value

### ISSUE THREAD

**Issue by ddobrin** [networknt/json-schema-validator#183]
When an OpenAPI specification declares an enum, and specifies it as being nullable, the consumer can send the values:
{...
field: null
...}

The validator identifies it correctly as nullable, however proceeds to look for null as a value in the enumerated fields.

It is a delta between OpenAPI and JSONSchema specifications:
-- https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values
-- http://spec.openapis.org/oas/v3.0.2

The issue can be fixed in a configurable manner in the validator without impacting performance

**Comment by stevehu** [comment]
We have a configuration for this type of use cases already. 

https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/SchemaValidatorsConfig.java

**Comment by harishvashistha** [comment]
@stevehu I could not see above configuration working for this example. We have recently onboarded with this library for schema validation with some existing migrated data and having issues with earlier validated resources. Can you help me with these example:

```
"schema": {
      "properties": {
        "values": {
          "type": "string",
          "nullable": true,
          "default": null
        }
      }
    }
```
Data:

```
{
    "values": null
 }
```

It is failing with this exception:

`null found, string expected`

Above handleNullableFields seems working only with oneOf and enum. Urgent help needed.

**Comment by stevehu** [comment]
You have to implicitly set the typeLoose flag to true when you initialize.

**Comment by harishvashistha** [comment]
@stevehu I have set this configuration for `SchemaValidatorsConfig` :

```
@Bean
    public SchemaValidatorsConfig schemaValidatorsConfig() {
        ApplyDefaultsStrategy applyDefaultsStrategy =
                new ApplyDefaultsStrategy(true, true, true);
        SchemaValidatorsConfig schemaValidatorsConfig = new SchemaValidatorsConfig();
        schemaValidatorsConfig.setTypeLoose(true);
        schemaValidatorsConfig.setApplyDefaultsStrategy(applyDefaultsStrategy);
        return schemaValidatorsConfig;
    }
```
But typeloose flag as true or false has not impact on my example above when null value is provided for resource during schema validation. I have put a debug point in library code. For my example method `public static boolean equalsToSchemaType(JsonNode node, JsonType schemaType, JsonSchema parentSchema, SchemaValidatorsConfig config) {` in class `JsonNodeUtil` is returning `false` when I am expecting it should return true when nullable is true with handleNullableField true as well. Because this code is returns true only for OneOf complex type, other types like string, integer it is returning false for them because of `state.isComplexValidator()` which is true only for OneOf case rest it is false for all other cases and this is in && predicate which causes all nullable setting to ignore.

```
ValidatorState state = (ValidatorState) CollectorContext.getInstance().get(ValidatorState.VALIDATOR_STATE_KEY);
            if(JsonType.NULL.equals(nodeType)) {
                if(state.isComplexValidator() && parentSchema != null) {
                    if( parentSchema.getParentSchema() != null && JsonNodeUtil.isNodeNullable(parentSchema.getParentSchema().getSchemaNode(), config) || JsonNodeUtil.isNodeNullable(parentSchema.getSchemaNode()) ) {
                        return true;
                    }
                }
            }
```

should we modify this code to work better. can you please have a look with my example above.
