### ISSUE TITLE
Collecting information while validating the schema.

### ISSUE THREAD

**Issue by prashanthjos** [networknt/json-schema-validator#249]

**Comment by prashanthjos** [comment]
Is it possible to collect some kind of information about the data while we are validating the given data against the schema ? For example if I want to collect certain Id’s mentioned in the data against  an array of domain values defined in the schema and return it back to the caller of the validate method. Essentially I need to maintain a context object about my validation, fill values into it during validation  and collect it at the end of validation.

**Comment by prashanthjos** [comment]
My understanding is to pass a context object across to all the implementations of validators, formats and keywords. This context object scope is limited to a single validation that is, it is reset after every validation of the Json data against the json schema. Starting with, this context object could be an extension to a simple map. We can let the API user create an instance of this context object and pass it to the validate method. Context object can collect information across all the formats, validators and keywords. Please let me know your thoughts.

**Comment by stevehu** [comment]
Without a detailed design, I cannot imagine how it works. As you have suggested, we can allow users to pass in a context object that indicates which validator will be used and what kind of data will be collected. In this case, we must check this context object in every validator to see if any data needs to be collected. This extra step would impact the performance across all validators in my opinion. Is there any better way that we can limit the impact? I think this is a useful extension for the library, but we need to carefully design it so that it won't impact most users. Would you be able to write something down or issue a PR so that we can have a base to discuss the details. Thanks.

**Comment by prashanthjos** [comment]
Yes. I can fork out the repo and come up with a pull request. I am trying to make sure that code changes to the existing code is minimal and has no performance impact. I will get back to you with a PR. Thank you.
