### ISSUE TITLE
Cache remote schema references

### ISSUE THREAD

**Issue by xaviarias** [networknt/json-schema-validator#27]
When referencing the same schema within the same parent JsonSchema, resources could be cached?
 
E.g.: 

"$ref": "https://domain.com/schemas/data_type.json#sub_type1"
and 
"$ref": "https://domain.com/schemas/data_type.json#sub_type2"

 Thanks

**Comment by stevehu** [comment]
If you understand your questions correctly, you want to confirm if these ref schemas are cached in memory during processing, then the answer is yes. All the schemas are loaded before hand and cached in memory so that we can have fast validation. We have a benchmark to compare with other popular Java implementations. 
https://github.com/networknt/json-schema-validator-perftest

**Comment by xaviarias** [comment]
Hi Steve!

My question was more regarding remote schemas. Every time `RefValidator` is fetching a schema, `JsonSchemaFactory` opens a new stream:

https://github.com/networknt/json-schema-validator/blob/0.1.6/src/main/java/com/networknt/schema/RefValidator.java#L59

Could we think in implementing a mechanism, for instance at the `JsonSchemaFactory` level, to avoid this overload? (E.g. a cache from URL -> JsonSchema)

**Comment by stevehu** [comment]
@xaviarias I got it. It should be cached. I will get it fixed once I have time and pull request is welcome.

**Comment by stevehu** [comment]
@xaviarias I looked into the code and found out the access to remote is only in the constructor of RefValidator. In this case, it should only be called once during initialization. It is cached in that way like other validators. Could you please test it out to verify it? Thanks.
