### ISSUE TITLE
Validator hangs on large json data files 

### ISSUE THREAD

**Issue by inbarweiss** [networknt/json-schema-validator#28]
Hello, 
I am currently working on improving our JSON validator using your library, but I had trouble with large files:
Currently, running on a JSON with a size of 86MB using the FGE library takes 43825ms, but with this library it took 242476ms.
When running on smaller files(1kb) this library had a huge advantage, especially on large quantities of small files(1952ms using this library vs 18228ms using FGE). 
I was wondering whether there is any configuration or settings that could help me with dealing with larger files, or whether this is a known issue. 

Thank you, 
Inbar Weiss

**Comment by stevehu** [comment]
@inbarweiss Frankly, I never tested with large data file and the library is designed to validate the request and response of [light-java-rest](https://github.com/networknt/light-java-rest) framework. Is it possible for you to share your data file and schema file? When I have time, I want to debug into it to figure out what is the root cause. BTW, what is your use case?

**Comment by inbarweiss** [comment]
Hey, thank you for the quick answer. 
I'm sorry, but I can't send you the data. 
I'm using the validator for validation process in Hadoop ecosystem using Hive UDF.

**Comment by stevehu** [comment]
I understand data is sensitive. And I guess it is an array of objects in the big json. I will try to reproduce it with some generated json laster on. Thanks.

**Comment by inbarweiss** [comment]
Thank you!

בתאריך 11 באפר׳ 2017 6:24 אחה״צ,‏ "Steve Hu" <notifications@github.com> כתב:

**Comment by stevehu** [comment]
@inbarweiss We have users with a large schema file complaining slowness but always successful. There are several issues regarding self-reference in the schema and I am guessing this might be the root cause for your use case. The recursive self-reference issue is addressed today by @davidvisiedo in https://github.com/networknt/json-schema-validator/issues/180
