### ISSUE TITLE
Consider not requiring HTTPS for custom meta schemas

### ISSUE THREAD

**Issue by dnedev** [networknt/json-schema-validator#314]
Hello,

Since release [`1.0.40`](https://github.com/networknt/json-schema-validator/releases/tag/1.0.40) custom meta schemas must be accessed over HTTPS. Unfortunately, some 3rd party schemas we use come from hosts that do not support HTTPS. As a result, we experienced a lot of schema validation issues and had to downgrade.

- Is it possible to disable the requirement that all custom schemas must be retrieved over HTTPS?
   - If not, would you consider adding an option for that?

Thanks!

**Comment by stevehu** [comment]
@dnedev We are trying to normalize the meta schema to https in order to find the matching meta schema instance. Users can still use HTTP for meta schema I think. Could you please submit a test case to reproduce the issue you have encountered? 

https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonSchemaFactory.java#L385

**Comment by hisener** [comment]
@stevehu Sorry for the delay. I created https://github.com/networknt/json-schema-validator/pull/400 to provide a failing test. Let me know what you think.
