### ISSUE TITLE
Compatible with Jackson 2.9.x

### ISSUE THREAD

**Issue by pan3793** [networknt/json-schema-validator#317]
It's an awesome project, I'm looking for a light tool to validate json message, I think this project is almost what I want.

I'm planning to integrate it to my Hadoop related project. I need to carefully evaluate every newly introduced tool, cause that Hadoop ecological dependence is already chaotic enough. 

I use Hadoop CDH-6.3.1, which depends on Jackson 2.9.9, and this project is build against Jackson 2.10.x now, with little code tune, it can pass the compile and test.

Furthermore, I think it makes sense to keep compatible with multi Jackson versions, or build a shaded Jackson version may be another good choices.

**Comment by stevehu** [comment]
One thing that I want to point out is Jackson 2.9.x has some security vulnerabilities and most organizations cannot use it due to security policy enforcement. All our repositories are constantly scanned by some banking customers and we update security issues promptly. I would highly recommend you upgrade your Hadoop ecosystem to the latest Jackson version if possible. If you have roadblocks to upgrade, I think your changes should be fine. Thanks.

**Comment by pan3793** [comment]
Thanks for your advice. I understand that keeping libs up to date is an ideal solution, but actually it's hard to implement. Hadoop ecosystem is consist of so many projects, and the distribution CDH which we choosen is half-open source. I think cloudera has spent lots of effort to make those components work together, any dependency version change may break the peace. 

It's a trade-off between usability and security, for us, we prefre to take a risk on sercurity rahter than break usability.

BTW, I don't think the changes I made to be compatible with Jackson 2.9.x will bring any security issue, just make it more universal. 

Again thanks for your reply, if your don't want to make it compatible with old jackson version, please close this issue and I will fork it to maintain a internal version. Considering that you take security very seriously, I think the ideal solution is build a shaded Jackson version and keep it up to date.

**Comment by stevehu** [comment]
To make it compatible with older Jackson version won't introduce any security risk. I am maintaining so many repositories and I know how hard to keep an application up-to-date. We are using light-bot regex-replace to update all the repositories in batch. I have published a new version 1.0.43; however, I would suggest you open an issue to Hadoop to get the Jackson upgraded as there are many security vulnerabilities since 2.9.x.
