### ISSUE TITLE
JRuby Joni dependency and its dependencies 

### ISSUE THREAD

**Issue by Vity01** [networknt/json-schema-validator#329]
The Readme.md homepage declares there are only 3 required dependencies, but the validator depedency also include `org.jruby.joni` dependency which includes jcodings.jar dependency  transitively (and it's pretty big jar >1MB) .
Is it really necessary? What's good for?

**Comment by stevehu** [comment]
The JSON schema specification is designed based on Javascript regex and there are some differences in Java regex implementation. For most users, they might not care about the differences and they are good with Java regex. If users want to ensure the regex syntax is the same as the specification, they can use the JRuby regex. I think we can make the dependency optional or provided so that the end-user can decide if they need to put it into the pom.xml file. I am open to all options to support all user's requirements. Any suggestions? Thanks.

**Comment by Vity01** [comment]
Yeah, please do the dependency optional.
