### ISSUE TITLE
Incorrect error description (NullPointerException) when using a non-uri value in the id field

### ISSUE THREAD

**Issue by antonovdmitriy** [networknt/json-schema-validator#339]
## Description
Insufficiently clear description of the error when using a non-uri value in the id field at the root of the schema element. It would be better to show a competent message about incorrect format

## Repeating
```
{
  "id": "JustSomeStringValue",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "field1":{
      "type": "string"
    }
  }
}
```
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V4);
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream("test.json");
        JsonSchema node =  factory.getSchema(is);```
**output**

![image](https://user-images.githubusercontent.com/5902197/97492075-1b4f1380-1974-11eb-96fa-026c1a8032ac.png)

**Comment by stevehu** [comment]
@AntonovDmitriy Thanks for raising it. I am wondering if you could submit a PR to get it fixed.

**Comment by ottomata** [comment]
Also, `$id` is not required to be a fully qualified URL.  At the Wikimedia Foundation [we use relative path URIs](https://techblog.wikimedia.org/2020/09/17/wikimedias-event-data-platform-json-event-schemas/) for `$id`s and provide base URIs when resolving them.  

I just tried to use this library but realized I can't because our relative path $ids  (e.g. "/entity/event/1.0.0") cause a similar exception. I think more recent versions have this NPE caught.  The exception I get is:

```
com.networknt.schema.JsonSchemaException: /test/event/1.0.0: null is an invalid segment for URI {2}
```

**Comment by hscissors** [comment]
Not to necrobump this, but I'm running into this exact issue. Our schema still loads, but it's still throwing the error in logs. Any work around?

**Comment by stevehu** [comment]
Have you tried the latest version 1.4.x? Let's open another issue for the new version if it is not resolved. Close this one.
