### ISSUE TITLE
Add discriminator support

### ISSUE THREAD

**Issue by slinkydeveloper** [networknt/json-schema-validator#35]
Hi,
I'm actually coding tools for OpenAPI 3 using your json schema validator. I know that it's a field out of JSON Schema Spec, but what do you think about implementing `discriminator` field of OpenAPI 3 spec? For more info: https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#fixed-fields-20

Thank you

**Comment by stevehu** [comment]
@slinkydeveloper I have read the spec and it looks like easy to implement. We are in a process to refactor the library in order to support different versions of draft spec from 4 to 6 as well as customized validators. I will keep this open until the architecture change is done. I am a user of OpenAPI spec and I have a [framework](https://github.com/networknt/light-rest-4j) to generate the code and utilize the spec to do the validation and jwt scope verification at runtime. It is my best interest to support you:)

**Comment by slinkydeveloper** [comment]
That's awesome thank you! I'm actually developing as gsoc student the support to openapi 3 inside vertx-web with runtime parameter validation and other stuff. If you want, take a look: https://github.com/slinkydeveloper/vertx-web/tree/designdriven/vertx-web/src/main/java/io/vertx/ext/web/validation

**Comment by stevehu** [comment]
closed with most features implemented.
