### ISSUE TITLE
Cannot resolve local reference $ref.

### ISSUE THREAD

**Issue by kohan14** [networknt/json-schema-validator#405]
Hi,
I'm having problems when dealing with local references from other folders.
My folder structure: 
├── resources
│           ├── Schema1.json
│           ├── TestFolder
  │           │             ├── Schema2.json

I want to use Schema2 and access its $ref pointing to Schema1, behind one directory.

Schema2.json
`	"properties": {
		"Dokument": {
			"$ref": "../Schema1.json#/definitions/Dokument"
		}
	}
`

I found no example on how to do it in docs, now i get:
`com.networknt.schema.JsonSchemaException: #/properties/Dokument/$ref: Reference ../Schema1.json#/definitions/Dokument cannot be resolved`

Maybe that's worth mentioning ?

Would appreciate some help, thanks.

**Comment by stevehu** [comment]
The local reference is not supported by the official specification because only the URL is supported. We have special handling to support the local reference but it only supports the local filesystem not the files from the resources. Frankly, I never tested the resources folder myself. If you want to get it supported, please create a test case and debug it to see where is the issue. I am sure it should be an easy update to support the resources within a jar file.

**Comment by stevehu** [comment]
@timothy-janssen Thanks a lot for your comment; it will benefit other users.
