### ISSUE TITLE
$ref to github

### ISSUE THREAD

**Issue by mahirgamal** [networknt/json-schema-validator#572]
Hi,

I am trying this code:
"$ref": "https://github.com/adewg/ICAR/blob/3340b2041f73afe47079426588bcef1eaf2b004e/enums/icarDepartureKindType.json",

but always getting this error:
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 7, column: 2]

and when I am testing locally it works perfect, any idea what's wrong?

![image](https://user-images.githubusercontent.com/86919381/168125162-42b5a34c-b07c-4a28-b1f0-af5cd1228925.png)

cheers,

**Comment by stevehu** [comment]
We have some issues connecting to the HTTPS site with the client.truststore configuration. This is the reason we need to move to Java 11 so that we can use the JDK 11 HTTP client instead of HttpConnection in Java 8, which is very limited. We do not want to introduce another client library as it will complicate the application dependency. There is a pending issue for that. Thanks.

**Comment by stevehu** [comment]
@mahirgamal I have tested the HTTPS access to public sites and it works. So my previous answer was wrong. Could you please submit a PR with a test case? I will find sometime to debug into it. Thanks.

**Comment by mahirgamal** [comment]
@stevehu thanks for your quick response. I did open Pull Request.
Cheers.

**Comment by fdutton** [comment]
Rejected the pull-request since it required adding a self-signed certificate to the trust-store.
