### ISSUE TITLE
`time` validation incomplete

### ISSUE THREAD

**Issue by JDziurlaj** [networknt/json-schema-validator#669]
I have a schema using `draft-07`. It has a property using `format: time`. When validating the following input `07:00:00-06:00`, `json-schema-validator` 1.0.72 generates an error `X: does not match the time pattern ^\d{2}:\d{2}:\d{2}(?:\.\d+)?$`. However, I believe my input to be valid per the [spec](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-7.3.1). It appears the `time-offset` may not be implemented.

**Comment by stevehu** [comment]
We used to have a regex to validate the DATE and DATETIME but switched to com.ethlo.time.ITU because it is tough to cover all use cases with regex. I through time format is much simpler and it is still using regex at https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonMetaSchema.java#L43

Could you please come up with an updated regex to cover your case? Or we can switch to ITU for time validation if necessary. Thanks.

**Comment by JDziurlaj** [comment]
I believe this would suffice `^\d{2}:\d{2}:\d{2}(?:\.\d+)?(Z|[\+-]\d{2}:\d{2})?$`. This adds support for the `time-offset` of [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).

**Comment by stevehu** [comment]
I think it makes sense. Can you submit a PR with your test case? We need a test case to ensure that your use case won't be broken when this regex is changed in the future. Thanks.

**Comment by JDziurlaj** [comment]
Do you want a real world schema (resource) or a MRE to test just this issue?
