### ISSUE TITLE
Time Field Validation Broken

### ISSUE THREAD

**Issue by constantin-baciu** [networknt/json-schema-validator#726]
I think that PR #704  has broken the time fields validation.

Fields with the format of "HH:mm:SS" are failing.
For example: "12:45:51" is failed with this error:

`does not match the time pattern ^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])(?:\.\d+)?(?:Z|[+-](?:(?:0[0-9]|2[0-3]):[0-5][0-9]))$`

I've noticed that the time format regex expression has been changed from:

`^(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]|(24:00:00))(?:\\.\\d+)?(Z|[+-]((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?$`

to

`^(?:(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])(?:\.\d+)?(?:Z|[+-](?:(?:0[0-9]|2[0-3]):[0-5][0-9]))$`

If I use a simple regex validator on the string above with both expressions, the new one doesn't find anything while the old one finds it alright.

**Comment by fdutton** [comment]
@constantin-baciu JSON Schema defines the time format using the definition from RFC 3339, which requires a time-zone offset. The old code incorrectly allowed for an optional time-zone offset and this cause some of the tests from the JSON Schema Test Suite to fail.

The JSON Schema specification allows validators to accept alternative representations but acknowledges that these are inherently non-portable. An example of such an alternative would be `partial-time` from RFC 3339, which accepts the example you provided but this also means that schemas must use `partial-time` as the format instead of `time`.

What are your thoughts?

**Comment by constantin-baciu** [comment]
@fdutton That makes sense. 
But, this breaks our integration with other providers (of which we have little to no control over).

I think I'll switch my schema from "time" to "regex" and add both expressions, until all the providers send files that are conforming to the RFC. 

Thanks!
