### ISSUE TITLE
Wrong message when having multiple error in unevaluatedProperties

### ISSUE THREAD

**Issue by jsinovassin** [networknt/json-schema-validator#746]
Version of the library: 1.0.81

When having multiple error when validating an object against a schema which have the unevaluatedProperties key. There is wrong information which are displayed in the error message thrown by the validation.

For example with the following schemas:

File: view.json
```
{
  "$id": "https://unomi.apache.org/schemas/json/events/view/1-0-0",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "self":{
    "vendor":"org.apache.unomi",
    "target" : "events",
    "name": "view",
    "format":"jsonschema",
    "version":"1-0-0"
  },
  "title": "ViewEvent",
  "type": "object",
  "allOf": [{ "$ref": "https://unomi.apache.org/schemas/json/event/1-0-0" }],
  "properties" : {},
  "unevaluatedProperties": false
}

```

File: event.json (used in allOf of view.json)
```
{
  "$id": "https://unomi.apache.org/schemas/json/event/1-0-0",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Event",
  "type": "object",
  "properties" : {
    "eventType" : {
      "type" : "string"
    },
    "profileId" : {
      "type" : "string"
    },
    "sessionId" : {
      "type" : "string"
    },
    "scope" : {
      "type" : "string"
    },
    "sourceId" : {
      "type" : "string"
    },
    "persistent" : {
      "type" : "boolean"
    }
  }
}

```

The object sent for validation:
(Call of the method here https://github.com/networknt/json-schema-validator/blob/master/src/main/java/com/networknt/schema/JsonSchema.java#L292)
```
{
    "itemId": "e3b4e553-6567-4a56-b27e-19220486873c",
    "itemType": "event",
     "scopxe": "systemsite",
     "eventType": "view",
     "sessionId": "dbcd7acb-683b-46ba-ada7-1626a8543680",
     "profileId": "6599229e-3968-4707-a61c-6881a8e453b6",
     "persistent": "noBooleanValue"
}
```

The result of the validation:
```
{
     "error": "There are unevaluated properties at following paths $.itemId, $.itemType, $.scopxe, $.eventType, $.sessionId, $.profileId, $.persistent"
}, {
    "error": "$.persistent: string found, but boolean is required"
}
```

In the previous example persistent does not contains a correct value and scopxe does not exists in the schema.
Only $.scopxe should be displayed in the error message, not $.itemId, $.itemType, $.eventType, $.sessionId, $.profileId, $.persistent. 
It's hard to understand the validation message with complex object with sub objects, because all properties of the objects are displayed even if they are correct.

If there is only unevaluated properties issue, the error message is correct. 

For example when trying to validate 
 ```
{
    "itemId": "e3b4e553-6567-4a56-b27e-19220486873c",
    "itemTypeInvalid": "event",
    "scopxe": "systemsite",
    "eventType": "view",
    "sessionId": "dbcd7acb-683b-46ba-ada7-1626a8543680",
    "profileId": "6599229e-3968-4707-a61c-6881a8e453b6",
    "persistent": true
}
```

we get a message that only contains the invalid properties: 
```
{
    "error": "There are unevaluated properties at following paths $.itemTypeInvalid, $.scopxe"
}

```

**Comment by fdutton** [comment]
@jsinovassin I agree that the error messages are less helpful in this case but, unfortunately, the code is behaving as described in the JSON Schema specification. At first, I was unsure so I doubled checked. I then contacted some people from the JSON Schema Test Suite project and they verified that this is the desired behavior but acknowledged that questions about `unevaluatedProperties` and `unevaluatedItems` are frequently raised. I think they may be considering alternatives for future versions of the spec.

This happens because validation of the properties occurs inside `allOf` and the validation of `allOf` fails because one of the properties fails to validate. Here is a response from a member of the JSON Schema Test Suite project:
> We determined that the best interpretation was that annotations are maintained within a subschema, but if an entire subschema fails validation, then its annotations are dropped and can't be seen by any higher subschemas.

We are open to suggestions on how to make the user experience better.

Here is the relevant portion of the specification (see the portion in italics below).

[Annotations and Assertions](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-annotations-and-assertions)
Schema objects that produce a false assertion result MUST NOT produce any annotation results, whether from their own keywords _or from keywords in subschemas_.

Note that the overall schema results may still include annotations collected from other schema locations. Given this schema:
```
{
    "oneOf": [
        {
            "title": "Integer Value",
            "type": "integer"
        },
        {
            "title": "String Value",
            "type": "string"
        }
    ]
}
```

Against the instance "This is a string", the title annotation "Integer Value" is discarded because the type assertion in that schema object fails. The title annotation "String Value" is kept, as the instance passes the string type assertions.
