### ISSUE TITLE
The constructor JsonSchema(ObjectMapper, JsonNode) is not visible

### ISSUE THREAD

**Issue by 2beers** [networknt/json-schema-validator#8]
Hello. I just found your library and I can't make it work.
I'm trying to test based on your example: https://github.com/networknt/json-schema-validator/blob/master/src/test/java/com/networknt/schema/JsonSchemaTest.java

But I'm receiving this error: 

> The constructor JsonSchema(ObjectMapper, JsonNode) is not visible

Am I doing something wrong?

**Comment by stevehu** [comment]
@2beers The JsonSchema object is constructed by JsonSchemaFactory. I have updated the README.md and added a section to show you several ways to construct JsonSchema from String, Stream, Url and JsonNode. Let me know if you still have question. Also, since your are interested in json schema validator, you might interest in my another project [light-java](https://github.com/networknt/light-java) which is the fastest API framework to build REST API or microservices in docker container.

**Comment by 2beers** [comment]
Yeah I looked in the source code and found JsonSchemaFactory. I'll check the other project light-java and give you a feedback.

**Comment by stevehu** [comment]
@2beers Thanks for bringing this issue up and I think it is very important. As I wrote the library myself I took a lot of things for granted. To update the README.md might be a good idea for now and I can use Hugo to build a static site for documentation later just like [light-java docs](https://networknt.github.io/light-java/)
