### ISSUE TITLE
Seems like error messages have encoding error with 1.0.87

### ISSUE THREAD

**Issue by MamoruAsagami** [networknt/json-schema-validator#870]
When I used the validator with version 1.0.86, I got the following strange message.

> $.id: integer ???????????????????????????string ????????????????????????

With, 1.0.(76|81|84|86), I got the following readable and reasonable message.

> $.id: integer found, string expected

Incidentally, I used it in Japan.
The attached file is a gradle project to reproduce the problem.

[JsonSchemaValidator.zip](https://github.com/networknt/json-schema-validator/files/12845242/JsonSchemaValidator.zip)

**Comment by stevehu** [comment]
We made some changes to add a lot more translations. UTF8 might not be enough for the Japanese language as it needs at least two bytes per character. Is there an easy way to reproduce it? Thanks.

**Comment by zxyao145** [comment]
Same problem with me. I got garbled text when using Chinese, is this because the *.properties file defaults to ISO-8859-1 encoding?

**Comment by zxyao145** [comment]
Perhaps it's because I'm using Java 8, and I found the solution from [stackoverflow](https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle), and it's working well. 

before:
![image](https://github.com/networknt/json-schema-validator/assets/24973084/32e1b4ee-abff-41e9-9ef2-963424d5c152)

now:
![image](https://github.com/networknt/json-schema-validator/assets/24973084/de6a34ff-59d0-4b02-abe0-a35110bf09c8)





Refer to this post: https://github.com/networknt/json-schema-validator/blob/master/doc/multiple-language.md, my approach is as follows:

1. copied the default multilingual file (from https://github.com/networknt/json-schema-validator/tree/master/src/main/resources) to my own resources folder and renamed it to `json-schema-validator-msg_zh_CN.properties`

2. define the UTF8Control . More see the [stackoverflow](https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle)
<details>

<summary>UTF8Control.java</summary>

```java
public class UTF8Control extends ResourceBundle.Control {

    public ResourceBundle newBundle
            (String baseName, Locale locale, String format, ClassLoader loader, boolean reload)
            throws IllegalAccessException, InstantiationException, IOException
    {
        // The below is a copy of the default implementation.
        String bundleName = toBundleName(baseName, locale);
        String resourceName = toResourceName(bundleName, "properties");
        ResourceBundle bundle = null;
        InputStream stream = null;
        if (reload) {
            URL url = loader.getResource(resourceName);
            if (url != null) {
                URLConnection connection = url.openConnection();
                if (connection != null) {
                    connection.setUseCaches(false);
                    stream = connection.getInputStream();
                }
            }
        } else {
            stream = loader.getResourceAsStream(resourceName);
        }
        if (stream != null) {
            try {
                // Only this line is changed to make it to read properties files as UTF-8.
                bundle = new PropertyResourceBundle(new InputStreamReader(stream, "UTF-8"));
            } finally {
                stream.close();
            }
        }
        return bundle;
    }
}
```

</details>

3. create the ResourceBundle 
```java
ResourceBundle myBundle = ResourceBundle
                .getBundle("json-schema-validator-msg",
                        Locale.SIMPLIFIED_CHINESE,
                        new UTF8Control()
                );
SchemaValidatorsConfig config = new SchemaValidatorsConfig();
config.setResourceBundle(myBundle);
```

**Comment by MamoruAsagami** [comment]
Information is that the default encoding was changed to UTF-8 since Java9.
So, they are encouraged to use Java9 or later version to run json-schema-validator.
As for myself, I decided to insert the following line to change the default locale of  JVM.

       Locale.setDefault(Locale.US);

Thanks, everybody and everything.
