### ISSUE TITLE
Custom Formats are not allowed for types other than Strings

### ISSUE THREAD

**Issue by gopichandch** [networknt/json-schema-validator#957]
https://github.com/networknt/json-schema-validator/blame/51fd82b420c3abde014f180ea109155de0d36480/src/main/java/com/networknt/schema/FormatValidator.java#L51

I'm trying to implement a custom Format for an integer type. But it doesn't validate if its not of String Type. Is there any reason not to support other types. Or am I missing something? Please let me know if we can remove that check.

**Comment by gopichandch** [comment]
Thanks a lot @justin-tay @stevehu . May I know when can we get the updated version.

**Comment by stevehu** [comment]
@gopichandch We usually wait for @justin-tay to update the pom.xml to indicate the next version is ready, as he is actively working on issues and enhancements in his forked repo. I see massive changes since the last release, so let's cut a tag 1.3.2. 

@justin-tay, you can create new branches in this repo, and it would be easier to merge between branches. Thanks a lot for your contributions. 

https://github.com/networknt/json-schema-validator/releases/tag/1.3.2
